name: CI
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-20.4
    steps:
      - name: print greeting
        run: echo "hello world..!"
      - name: print goodbye
        run: echo "done by -- Akshay Mithari..!"
    
