name: test-frontend
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -   name: Get code
                uses: actions/checkout@v4.1.1
            -   name: Install node js
                uses: actions/setup-node@4
                with:
                    node-version: 21
            -   name: Install dependencies
                run : npm ci
            -   name: Code test
                run : npm test